### ISSUE TITLE
Where is the `query-connection` repo

### ISSUE THREAD

**Issue by Alynva** [c-ridgway/node-graceful-shutdown-manager#1]
Is the [query-connection](https://www.npmjs.com/package/query-connection) private? I've a PR in mind.

**Comment by c-ridgway** [comment]
Please make as many pull requests as you like at: https://github.com/c-ridgway/node-query-connection

I've just updated all the libraries.

> Its where you changed the `process.PATH`, you uses `process.cwd()` as the lib root folder, but if I run it in other place, it wound't be right. Changing the `path.join(process.cwd(), 'bin', ...)` to `path.join(__dirname, '..', 'bin', ...)` works. My friend did it here [at15four2020/query-connection@dfe70f8](https://github.com/at15four2020/query-connection/commit/dfe70f8e49d7b12e4915e4505423de26ea4d7fdc)

You're absolutely right. This was initially written in a hurry for a specific usecase and was my first published project. I welcome any fixes you'd like to make as I'm a little overloaded right now.

> And i think you're not rejecting `error` nor `stderr` there

That'd be right. I didn't fully understand promises back then and their lifecycle.

**Comment by Alynva** [comment]
Thank you
